print("Welcome To HotelEaseCalc")
print("Please Enter Your Details Below: - ")
a = input("Enter first item: ")
a1 = input("Enter price: - ")
b = input("\nEnter second item: ")
b1 = input("Enter price: - ")
c = input("\nEnter third item: ")
c1 = input("Enter price: - ")
d = input("\nEnter fourth item: ")
d1 = input("Enter price: - ")